GoogleCloudPlatform/gke-networking-recipes

multi-cluster-ingress/multi-cluster-external-ingress/config-cluster.yaml

Removed extra route from multi-cluster example

fixed minor issue

---

ingress/external-ingress-basic/README.md

Update repo path in `git clone` command.

Update repo path.

---

ingress/external-ingress-basic/README.md

fixed cd command:
ORIG: cd gke-networking-recipes/external-ingress-basic # doesnt work
FIX: cd gke-networking-recipes/ingress/external-ingress-basic/ # does
-- ricc@

Update README.md (fix cd command)

---

README.md
cluster-setup.md
multi-cluster-ingress/multi-cluster-blue-green-cluster/README.md
multi-cluster-ingress/multi-cluster-blue-green-cluster/app.yaml
multi-cluster-ingress/multi-cluster-blue-green-cluster/ingress.yaml
multi-cluster-ingress/multi-cluster-blue-green-cluster/patch.yaml
multi-cluster-ingress/multi-cluster-ingress-basic/README.md
multi-cluster-ingress/multi-cluster-ingress-basic/app.yaml

added blue-green cluster instructions and some edits to cluster config instructions as well as MCI basic.

Mci blue green cluster

---

gateway/single-cluster/regional-l7-ilb/README.md
gateway/single-cluster/regional-l7-ilb/app-v1.yaml
gateway/single-cluster/regional-l7-ilb/app-v2.yaml
gateway/single-cluster/regional-l7-ilb/gateway.yaml
gateway/single-cluster/regional-l7-ilb/route.yaml
gateway/single-cluster/regional-l7-ilb/single-regional-l7-ilb-recipe.yaml

Added recipe for configuring a Regional L7 Internal Load Balancer on a single cluster via Gateway API

Single Cluster Regional L7 ILB with Gateway API

---

gateway/single-cluster/global-l7-xlb-https-backend/README.md
gateway/single-cluster/global-l7-xlb-https-backend/single-cluster-global-l7-xlb-https-backend.yaml

GKE Gateway in Single Cluster with HTTPS backend

---

ingress/single-cluster/ingress-external-basic/README.md

Fix image links in README

---

gateway/docs/store-autoscale.yaml

This fixes a small error in one of the docs YAMLs for Gateway traffic management

fixes yaml error

---

cluster-setup.md

Discovered and fixed typo while reading the docs

Fixed: Anthos service mesh typo

---

archive/demo-app.yaml
gateway/docs/site-deploy.yaml
gateway/docs/store-autoscale.yaml
gateway/docs/store-deploy.yaml
gateway/docs/store-traffic-deploy.yaml
gateway/docs/store-v1v2german-deploy.yaml
gateway/gke-gateway-controller/app/site.yaml
gateway/gke-gateway-controller/app/store.yaml
gateway/gke-gateway-controller/demo-app.yaml
gateway/gke-gateway-controller/gateway-user-guide-app.yaml
gateway/gke-gateway-controller/multi-cluster-gateway/store.yaml
gateway/gke-gateway-controller/multi-tenant-demo-app.yaml
gateway/single-cluster/global-l7-xlb-https-backend/single-cluster-global-l7-xlb-https-backend.yaml
gateway/single-cluster/global-l7-xlb/app.yaml
gateway/single-cluster/regional-l7-ilb/app-v1.yaml
gateway/single-cluster/regional-l7-ilb/app-v2.yaml
gateway/single-cluster/regional-l7-ilb/single-regional-l7-ilb-recipe.yaml
service-directory/cluster-ip-service/cluster-ip-service.yaml
service-directory/headless-service/headless-service.yaml
service-directory/internal-lb-service/internal-lb-service.yaml
service-directory/nodeport-service/nodeport-service.yaml
services/multi-cluster/mcs-basic/app.yaml
services/single-cluster/external-lb-service/external-lb-service.yaml
services/single-cluster/internal-lb-service/internal-lb-service.yaml

update whereami to v1.2.10

---

.gitignore
ingress/single-cluster/ingress-asm-multi-backendconfig/README.md
ingress/single-cluster/ingress-asm-multi-backendconfig/backend-services.yaml
ingress/single-cluster/ingress-asm-multi-backendconfig/istio-ingressgateway-service.yaml

Create Recipe for using multiple BackendConfigs for multiple ports on istio

---

gateway/multi-cluster/mcg-internal-basic/gke-1/app-v1.yaml
gateway/multi-cluster/mcg-internal-basic/gke-2/app-v2.yaml
gateway/multi-cluster/mcg-internal-blue-green/cluster-blue-app.yaml
gateway/multi-cluster/mcg-internal-blue-green/cluster-green-app.yaml
ingress/multi-cluster/mci-asm-https-e2e/app.yaml
ingress/multi-cluster/mci-basic/app.yaml
ingress/multi-cluster/mci-blue-green-cluster/app.yaml
ingress/multi-cluster/mci-frontend-config/app.yaml
ingress/multi-cluster/mci-https-e2e/app.yaml
ingress/single-cluster/ingress-asm-multi-backendconfig/backend-services.yaml
ingress/single-cluster/ingress-cloudarmor/cloudarmor-ingress.yaml
ingress/single-cluster/ingress-custom-http-health-check/custom-http-hc-ingress.yaml
ingress/single-cluster/ingress-external-basic/external-ingress-basic.yaml
ingress/single-cluster/ingress-https/secure-ingress.yaml
ingress/single-cluster/ingress-iap/iap-ingress.yaml
ingress/single-cluster/ingress-internal-basic/internal-ingress-basic.yaml
ingress/single-cluster/ingress-nginx/ingress-nginx.yaml

i'd missed a bunch of other references - this should clear it up

fixing other whereami references

---

gateway/single-cluster/global-l7-xlb-https-backend/README.md
gateway/single-cluster/global-l7-xlb-https-backend/single-cluster-global-l7-xlb-https-backend.yaml

The AppProtocol field is now supported.

Have example use AppProtocol field instead of annotation.

---

.github/workflows/documentation.yaml
.mlc_config.json
CONTRIBUTING.md
gateway/multi-cluster/mcg-internal-blue-green/README.md
ingress/multi-cluster/mci-blue-green-cluster/README.md
ingress/single-cluster/ingress-asm-multi-backendconfig/README.md
ingress/single-cluster/ingress-https/README.md
ingress/single-cluster/ingress-nginx/README.md
service-directory/README.md
service-directory/cluster-ip-service/README.md
service-directory/headless-service/README.md
service-directory/internal-lb-service/README.md
service-directory/nodeport-service/README.md

I found a lot of broken links in the repo, so I've fixed that.
I've also added workflow with [markdown link check](https://github.com/tcort/markdown-link-check) to avoid this in future.

Fixed broken links and added workflow to check this

---

ingress/single-cluster/ingress-external-basic/README.md

Fixed port numbers in ingress-external-basic README

---

gateway/docs/store-autoscale.yaml

https://github.com/GoogleCloudPlatform/gke-networking-recipes/issues/127

update gateway API for store-autoscale

---

ingress/single-cluster/ingress-nginx/README.md

Update typo in filename and validation command.

Update typo in ingress-nginx recipe

---

ingress/single-cluster/ingress-custom-default-backend/README.md
ingress/single-cluster/ingress-custom-default-backend/ingress-custom-default-backend.yaml

Create example yaml for adding custom default backend and README for instructions.

Add recipe for ingress with custom default backend.

---

ingress/single-cluster/ingress-custom-http-health-check/README.md
ingress/single-cluster/ingress-custom-http-health-check/custom-http-hc-ingress.yaml

* Updated Ingress apiVersion to networking.k8s.io/v1
* Refactored README using repository's guidelines
* Added network manifests to README

Update custom-http-health-check recipe

---

.mlc_config.json

Ignore vendor folder for markdown link checks

Ignore vendor folder for markdown link checks

---

.github/workflows/documentation.yaml

fix github action error

---

go.mod
go.sum
vendor/github.com/kr/pretty/.gitignore
vendor/github.com/kr/pretty/License
vendor/github.com/kr/pretty/Readme
vendor/github.com/kr/pretty/diff.go
vendor/github.com/kr/pretty/formatter.go
vendor/github.com/kr/pretty/pretty.go
vendor/github.com/kr/pretty/zero.go
vendor/github.com/kr/text/License
vendor/github.com/kr/text/Readme
vendor/github.com/kr/text/doc.go
vendor/github.com/kr/text/indent.go
vendor/github.com/kr/text/wrap.go
vendor/github.com/rogpeppe/go-internal/LICENSE
vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem.go
vendor/github.com/rogpeppe/go-internal/fmtsort/sort.go
vendor/modules.txt

Add pretty package for pretty-format printing.

Add pretty package

---

test/utils/crud.go
test/utils/parser.go
test/utils/parser_test.go

Use controller-runtime client to manage k8s resources.

Create yaml parser

---

Makefile
test/main_test.go
test/utils.go
test/utils/project_holder.go

Release boskos project after test run.

Release boskos project after run.

---

Makefile
test/main_test.go
test/utils.go
test/utils/cluster.go
test/utils/framework.go
test/utils/utils.go

Create Framework.go to setup project and other test resources.

Create test Framework.

---

ingress/single-cluster/ingress-asm-multi-backendconfig/backend-services.yaml
ingress/single-cluster/ingress-asm-multi-backendconfig/istio-ingressgateway-service.yaml

Update asm recipes to deploy gateway before sending traffic.

Update asm recipes to deploy gateway before sending traffic.

---

ingress/single-cluster/ingress-custom-default-backend/cleanup.sh
ingress/single-cluster/ingress-custom-default-backend/run-test.sh
ingress/single-cluster/ingress-custom-default-backend/setup.sh

* Add ingress custom default backend test.

Add test for ingress custom default backend.

---

ingress/single-cluster/ingress-external-basic/run-test.sh
ingress/single-cluster/ingress-internal-basic/cleanup.sh
ingress/single-cluster/ingress-internal-basic/run-test.sh
ingress/single-cluster/ingress-internal-basic/setup.sh

* Add genereate_config.sh to generate config for tests. It should be run before running tests.
* Add tests for ingress internal and external.

Add internal and external test

---

ingress/single-cluster/ingress-custom-http-health-check/cleanup.sh
ingress/single-cluster/ingress-custom-http-health-check/run-test.sh
ingress/single-cluster/ingress-custom-http-health-check/setup.sh

* Add test for ingress-custom-http-health-check.

Add test for ingress-custom-http-health-check

---

ingress/single-cluster/ingress-asm-multi-backendconfig/cleanup.sh
ingress/single-cluster/ingress-asm-multi-backendconfig/run-test.sh
ingress/single-cluster/ingress-asm-multi-backendconfig/setup.sh

* Add test for ingress-asm. Since asm requires a different cluster configuration, we will not use setup_gke_basic.

Add ingress-asm-multi-backendconfig test.

---

ingress/single-cluster/ingress-https/README.md
ingress/single-cluster/ingress-https/cleanup.sh
ingress/single-cluster/ingress-https/run-test.sh
ingress/single-cluster/ingress-https/secure-ingress.yaml
ingress/single-cluster/ingress-https/setup.sh

* Add ingress-https test. Rename ssl policy name since it has a naming collision with ingress-grpc recipe.

Add test for ingress-https.

---

CONTRIBUTING.md
README.md
test/README.md
test/test_example/cleanup.sh
test/test_example/run-test.sh
test/test_example/setup.sh

* Add template and instruction for new recipe test in test/README.md.
* Update Contribution.md and README.md for newly created recipes.

Add templates for recipe test files, and update Contribution.md.

---

gateway/bbr/gcphealthcheckpolicy.yaml
gateway/bbr/gcproutingextension.yaml

[InferenceGateway] Add GCP-specific YAMLs for body-based routing extension
