GoogleCloudPlatform/gke-networking-recipes

gateway/gke-gateway-controller/multi-cluster-gateway/internal-http-gateway.yaml, gateway/gke-gateway-controller/multi-cluster-gateway/internal-route-stage-1.yaml, gateway/gke-gateway-controller/multi-cluster-gateway/internal-route-stage-2.yaml, gateway/gke-gateway-controller/multi-cluster-gateway/internal-route-stage-3.yaml, gateway/gke-gateway-controller/multi-cluster-gateway/internal-route-stage-4.yaml, gateway/gke-gateway-controller/multi-cluster-gateway/private-store-route.yaml, gateway/gke-gateway-controller/multi-cluster-gateway/public-store-route.yaml, gateway/gke-gateway-controller/multi-cluster-gateway/store-west-1-service.yaml, gateway/gke-gateway-controller/multi-cluster-gateway/store-west-2-service.yaml
This updates the YAMLs used by the docs here: https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-multi-cluster-gateways#prerequisites
These aren't recipes per-se but they are a useful place to store these YAMLs
=> updating YAMLs referenced by Gateway controller docs pages

ingress/multi-cluster/mci-https-backend/README.md, ingress/multi-cluster/mci-https-backend/app.yaml, ingress/multi-cluster/mci-https-backend/haproxy.cfg, ingress/multi-cluster/mci-https-backend/haproxy/haproxy.cfg, ingress/multi-cluster/mci-https-backend/ingress.yaml
This recipe provides sample code to use GKE multi-cluster ingress with HTTPS backend. The sample code uses an HAPROXY sidecar with self-signed certificate to simulate HTTPS backend in GKE.
=> added multi-cluster ingress end to end https recipe

README.md, ingress/single-cluster/ingress-nginx/README.md, ingress/single-cluster/ingress-nginx/ingress-nginx.yaml
Adding Recipe for basic ingress with with an NGNIX controller. In order to keep this simple, some optional steps (like installing a certification manager) have been omitted. 
resolves #15
=> Adding recipe for ingress-nginx

gateway/docs/README.md, gateway/docs/site-deploy.yaml, gateway/docs/store-autoscale.yaml, gateway/docs/store-deploy.yaml, gateway/docs/store-traffic-deploy.yaml, gateway/docs/store-v1v2german-deploy.yaml, gateway/docs/store-west-1-service.yaml, gateway/docs/store-west-2-service.yaml
@boredabdel I am centralizing reference manifests that the docs use into specific folders. Right now there are some docs references in https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/gateway/gke-gateway-controller but there are some extra manifests in there that aren't needed and I'd like to get rid of the junk. This will entail the following:
1) Merge this /docs folder
2) Each manifest has a reference back to the docs page that references it. This ensures that any changes in the docs or vice-versa are made considering both so they are not out of alignment.
3) Once I have updated the product docs to point to these manifests in the /docs folder we can remove /gateway/gke-gateway-controller folder
lmk if that makes sense to you!
=> Product docs manifest folder

gateway/grpc/README.md, gateway/grpc/fe-deployment.yaml, gateway/grpc/my-gateway.yaml, ingress/single-cluster/ingress-custom-grpc-health-check/README.md, ingress/single-cluster/ingress-custom-grpc-health-check/example/README.md, ingress/single-cluster/ingress-custom-grpc-health-check/example/fe-deployment.yaml, ingress/single-cluster/ingress-custom-grpc-health-check/grpc-hc-proxy.yaml
The original container registry reference `gcr.io/cloud-solutions-images/` is not longer accessible.
This PR updates the yaml files to point to `docker.io`.  Also notes that cutomers are encouraged to generate and manage/host their own image (since `docker.io/` is rate limited.
Updates instructions for gateway to install CRDs first.
=> Change container image registry for grpc healthcheck

gateway/docs/store-autoscale.yaml
The example references the v0.4.3 CRD which uses the v1alpha2 schema.  Update the example to conform to this schema.
=> Update example to support v1alpha2 schema 

gateway/docs/store-autoscale.yaml
This preview feature will be replaced by a different mechanism.
=> Remove mention of max-rate-per-endpoint.

.gitignore, cluster-setup.md, ingress/multi-cluster/mci-asm-https-e2e/README.md, ingress/multi-cluster/mci-asm-https-e2e/app.yaml, ingress/multi-cluster/mci-basic/README.md, ingress/multi-cluster/mci-blue-green-cluster/README.md, ingress/multi-cluster/mci-https-e2e/README.md, ingress/multi-cluster/mci-https-e2e/app.yaml, ingress/multi-cluster/mci-https-e2e/dns-spec-bar.yaml, ingress/multi-cluster/mci-https-e2e/dns-spec-foo.yaml, ingress/multi-cluster/mci-https-e2e/ingress.yaml, ingress/single-cluster/ingress-cloudarmor/README.md, ingress/single-cluster/ingress-custom-http-health-check/README.md, ingress/single-cluster/ingress-external-basic/README.md, ingress/single-cluster/ingress-https/README.md, ingress/single-cluster/ingress-iap/README.md, ingress/single-cluster/ingress-internal-basic/README.md, ingress/single-cluster/ingress-nginx/README.md, service-directory/cluster-ip-service/README.md, service-directory/headless-service/README.md, service-directory/internal-lb-service/README.md, service-directory/nodeport-service/README.md, services/multi-cluster/mcs-basic/README.md, services/single-cluster/external-lb-service/README.md, services/single-cluster/internal-lb-service/README.md
- Unifying bash across all examples
- Fixing some typos
- Making the whereami spit out headers for the asm-https-e2e recipes
=> Fixing some issues with multi-cluster and unifiying some stuff across the recipes

ingress/single-cluster/ingress-https/README.md, ingress/single-cluster/ingress-https/secure-ingress.yaml
- The `networking.k8s.io/v1beta1` API versions of Ingress is no longer served as of kubernetes v1.22 ([link](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)). Updated the api version to `networking.k8s.io/v1` and related fields that changed.
- Fixed `cd` command in README
- Fixed Ingress manifest in README
=> Fix ingress-https recipe

ingress/single-cluster/ingress-internal-basic/internal-ingress-basic.yaml
Change networking.k8s.io/v1beta1 to networking.k8s.io/v1 since v1beta1 is no longer served as of v1.22
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingressclass-v122
Update the ingress rule path
=> Change networking.k8s.io/v1beta1 to networking.k8s.io/v1 for internal ingress recipe

gateway-api/config/servicepolicies/crd/standard/gcpgatewaypolicies.yaml
Closes: https://github.com/GoogleCloudPlatform/gke-networking-recipes/issues/130
This PR adds the `gcpgatewaypolicies.networking.gke.io` introduced with https://cloud.google.com/kubernetes-engine/docs/how-to/configure-gateway-resources#configure_global_access. This CRD was grabbed directly from a GKE 1.24 cluster with gateway API. 
```
❯ kcl get crd gcpgatewaypolicies.networking.gke.io
NAME                                   CREATED AT
gcpgatewaypolicies.networking.gke.io   2023-03-17T15:13:00Z
```
=> Add gatewaypolicies CRD schema

test/main_test.go, test/utils.go
Add TestHelloWorld to set up prow, and add more loggings for boskos project rental.
=> Add TestHelloWorld to set up prow, and add more loggings for boskos project rental.

test/main_test.go
Provide an actual logger implementation for controller-runtime client. Logs from controller-runtime client won't be displayed without a logger.
=> Add a logger to controller-runtime client.

Makefile, ingress/single-cluster/ingress-https/README.md, test/helper.sh
* setup_gke_basic and cleanup_gke_basic for basic test cleanup and setup.
* setup_ilb for ilb specific setup(proxy-only subnet and firewall)
* wait_for_ingress_ip and wait_for_managed_cert to wait for resource provision.
* validate_traffic to validate load balancer traffic.
* get_hash to generate hash based on the given string. Used to generate suffix for test resources.
=> Create helper functions for recipe test.

Makefile, test/helper.sh
* Add wait_for_glbc_deletion to wait for all ingress resources cleaned up before deleting cluster.
* Update test timeout so test won't keep hanging.
=> Update test timeout and add wait_for_glbc_deletion for ingress resources cleanup.

ingress/single-cluster/ingress-cloudarmor/cleanup.sh, ingress/single-cluster/ingress-cloudarmor/run-test.sh, ingress/single-cluster/ingress-cloudarmor/setup.sh
* Add test for ingress-cloudarmor.
=> Add test for ingress-cloudarmor.

ingress/single-cluster/ingress-nginx/README.md, ingress/single-cluster/ingress-nginx/cleanup.sh, ingress/single-cluster/ingress-nginx/run-test.sh, ingress/single-cluster/ingress-nginx/setup.sh
* Add test for ingress-nginx.
* Add clarification in README that GKE is not responsible for nginx controller issue.
=> Add test for ingress-nginx.

test/helper.sh
* Extract glbc resource names from ingress object since default-backend backend service and NEG cannot be identified based on ingress name.
* Add get_or_create_oauth_brand and get_oauth_client for getting OAuth client id and secret.
* Add --context option to kubectl commands so functions can be run when multiple clusters are created, and a helper function to get the test context.
* Add an option for check_http_status to skip ssl verification.
=> Update glbc deletion and check_http_status. Add OAuth and kubectl context helper.

test/helper.sh, test/recipe_test.go
* Extend check traffic wait time from 60x5s=5min to 180x5=15min since existing tests are failing due to insufficient wait time.
* Update skip test message in recipe_test.go.
=> Additional attempts for check_http_traffic, and update skip test message

ingress/single-cluster/ingress-iap/cleanup.sh, ingress/single-cluster/ingress-iap/run-test.sh, ingress/single-cluster/ingress-iap/setup.sh
* Add test for ingress iap.
* In the test, OAuth credential will be genereated and used in kubectl secret.
* User needs to have a valid domain name and specify DNS record as environment variable. A valid support email is also needed if OAuth Brand doesn't exist in the running project.
=> Add test for ingress iap.

test/helpers/hash.sh, test/helpers/ingress.sh, test/helpers/managed_cert.sh, test/helpers/oAuth.sh, test/helpers/setup.sh, test/helpers/validation.sh, test/main_test.go, test/utils/utils.go
* Move test/utils.go to test/utils/utils.go.
* Break test/helper.sh into separate functions in test/helpers, and source them from test/helper.sh.
=> Refactor test/helper.sh and test/utils.go

ingress/single-cluster/ingress-asm-multi-backendconfig/cleanup.sh, ingress/single-cluster/ingress-asm-multi-backendconfig/run-test.sh, ingress/single-cluster/ingress-asm-multi-backendconfig/setup.sh, ingress/single-cluster/ingress-https/cleanup.sh, ingress/single-cluster/ingress-https/run-test.sh, ingress/single-cluster/ingress-https/setup.sh, ingress/single-cluster/ingress-iap/cleanup.sh, ingress/single-cluster/ingress-iap/run-test.sh, ingress/single-cluster/ingress-iap/setup.sh
* Skip the test if environment variables are not set. If we need to run these tests, we would explicitly set the corresponding variables.
=> Skip tests instead if environment variables are not set.

gateway-api/config/servicepolicies/crd/standard/gcpbackendpolicies.yaml
**Description**
This PR adds the gcpbackendpolicies.networking.gke.io since LBPolicy was replaced by it, see here: https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api#policy. 
This CRD was grabbed directly from a GKE 1.26 cluster with gateway API.
=> Add gcpbackendpolicies CRD schema

test/recipe_test.go
* We observe issues when starting all jobs together because this can lead to a race condition with multiple writes to kube config file, since all clusters will be finished at roughly the same time.
* Thus, we introduce a sleep after each job so clusters won't all be created at the same time.
/assign @boredabdel
=> Introduce sleep after running each recipe.

test/recipe_test.go
* Since t.Parallel pauses and resumes all jobs at the same time, sleep after t.Run wouldn't work. Instead, we should sleep after t.Parallel. See PR#187 for context.
/assign @boredabdel
=> Fix sleep after job

gateway/docs/store-autoscale.yaml
Updated example to match the traffic-based workload horizontal autoscaling updated API.
The previous API (an annotation on Service) is still temporarily supported but deprecated. Users should switch to the new `maxRatePerEndpoint` field on `GCPBackendPolicy`.
=> Updated example following traffic-based autoscaling GA launch.
